# Generated by Django 5.0.6 on 2024-05-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('dateApplied', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
