# Generated by Django 5.0.6 on 2024-05-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_delete_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dateApplied',
            field=models.DateField(),
        ),
    ]
