# Generated by Django 5.0.6 on 2024-05-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('I', 'Interviewing'), ('O', 'Offer'), ('R', 'Rejected'), ('C', 'Closed')], default='A', max_length=1),
        ),
    ]
