# Generated by Django 5.0.6 on 2024-06-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_application_jobid_alter_application_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interviewing', 'Interviewing'), ('Offer', 'Offer'), ('Closed', 'Closed')], default='Applied', max_length=12),
        ),
    ]
